#!/bin/sh

echo Running aclocal...
aclocal || exit

echo Running libtoolize --copy --force...
libtoolize --copy --force || exit

echo Running autoconf...
autoconf || exit

echo Running autoheader...
autoheader || exit

echo Running automake --gnu --add-missing --copy...
automake --gnu --add-missing --copy
