#!/bin/bash

# the editor you wish to use
EDITOR="vim"
# command line arguments to that editor
EDITORARGS="";
# command line arguments to diff (used to get changes)
DIFFARGS="-u";
# command line arguments to date (used to timestamp changes)
DATEARGS="+%A %B %d, %G %r %Z"

if [ "$EDITOR" = "" ]; then
	echo "No editor is set! You must set the EDITOR variable in the script file";
	exit 1;
fi

if [ "$1" = "" ]; then echo "No option!"; exit 1; fi

NEWFILE="no";
if [ ! -f "$1" ]; then
	echo -n "$1 does not exist! Would you like to create it? [y/n] ";
	read -a CHOICE;
	if [ "$CHOICE" = "y" ]; then touch $1; NEWFILE="yes";
	elif [ "$CHOICE" = "n" ]; then exit 0;
	else echo "Please type y or n"; exit 1;
	fi
fi

if [ -f $1.bkup ]; then
	echo "$1 is already being edited!";
	exit 1;
fi

cp $1 $1.bkup;

$EDITOR $EDITORARGS $1;

if [ $? -eq 126 -o $? -eq 127 ]; then
	echo "Editor $EDITOR does not exist or is not an executable. Please fix this."
	exit 1;
fi

if [ "`diff $1.bkup $1`" != "" ]; then
	echo -n "Enter a short description of this edit: ";
	read -a DESC;

	if [ ! -f ChangeLog ]; then touch ChangeLog; fi
	cp ChangeLog ChangeLog.cpy;

	DESCR="";
	if [ "$NEWFILE" = "yes" ]; then DESCR="NEW FILE: ${DESC[@]}";
	else DESCR="${DESC[@]}";
	fi

echo "-- `date "$DATEARGS"` --
-- $DESCR --

`diff $DIFFARGS $1.bkup $1`

" > ChangeLog;

	cat ChangeLog.cpy >> ChangeLog;
	rm ChangeLog.cpy;
fi

rm $1.bkup;
